# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Upload.ui'
#
# Created: Fri May 20 08:02:48 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Upload(object):
    def setupUi(self, Upload):
        Upload.setObjectName("Upload")
        Upload.resize(700, 856)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Upload.sizePolicy().hasHeightForWidth())
        Upload.setSizePolicy(sizePolicy)
        Upload.setMinimumSize(QtCore.QSize(700, 0))
        Upload.setMaximumSize(QtCore.QSize(650, 16777215))
        Upload.setAutoFillBackground(False)
        Upload.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Upload)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid_Status = QtGui.QGridLayout()
        self.grid_Status.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.grid_Status.setObjectName("grid_Status")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_grid = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_grid.sizePolicy().hasHeightForWidth())
        self.button_grid.setSizePolicy(sizePolicy)
        self.button_grid.setMinimumSize(QtCore.QSize(0, 0))
        self.button_grid.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_grid.setObjectName("button_grid")
        self.horizontalLayout_8.addWidget(self.button_grid)
        self.grid_Status.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_grid = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_grid.sizePolicy().hasHeightForWidth())
        self.label_grid.setSizePolicy(sizePolicy)
        self.label_grid.setText("")
        self.label_grid.setOpenExternalLinks(True)
        self.label_grid.setObjectName("label_grid")
        self.grid_Status.addWidget(self.label_grid, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_path = QtGui.QToolButton(self.centralwidget)
        self.button_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_path.sizePolicy().hasHeightForWidth())
        self.button_path.setSizePolicy(sizePolicy)
        self.button_path.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.button_path.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_path.setArrowType(QtCore.Qt.NoArrow)
        self.button_path.setObjectName("button_path")
        self.horizontalLayout.addWidget(self.button_path)
        self.grid_Status.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_session = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_session.sizePolicy().hasHeightForWidth())
        self.button_session.setSizePolicy(sizePolicy)
        self.button_session.setMinimumSize(QtCore.QSize(0, 0))
        self.button_session.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.button_session.setArrowType(QtCore.Qt.NoArrow)
        self.button_session.setObjectName("button_session")
        self.horizontalLayout_7.addWidget(self.button_session)
        self.grid_Status.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_session = QtGui.QLabel(self.centralwidget)
        self.label_session.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_session.setText("")
        self.label_session.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_session.setOpenExternalLinks(True)
        self.label_session.setObjectName("label_session")
        self.horizontalLayout_10.addWidget(self.label_session)
        self.label_user = QtGui.QLabel(self.centralwidget)
        self.label_user.setText("")
        self.label_user.setObjectName("label_user")
        self.horizontalLayout_10.addWidget(self.label_user)
        self.grid_Status.addLayout(self.horizontalLayout_10, 0, 1, 1, 1)
        self.label_path = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.grid_Status.addWidget(self.label_path, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.grid_Status)
        self.frame_settings = QtGui.QHBoxLayout()
        self.frame_settings.setObjectName("frame_settings")
        self.verticalLayout.addLayout(self.frame_settings)
        self.tree_files = FilesView(self.centralwidget)
        self.tree_files.setEnabled(True)
        self.tree_files.setAutoScrollMargin(0)
        self.tree_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tree_files.setAlternatingRowColors(True)
        self.tree_files.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tree_files.setIndentation(10)
        self.tree_files.setRootIsDecorated(True)
        self.tree_files.setUniformRowHeights(True)
        self.tree_files.setItemsExpandable(True)
        self.tree_files.setExpandsOnDoubleClick(True)
        self.tree_files.setObjectName("tree_files")
        self.tree_files.header().setVisible(True)
        self.verticalLayout.addWidget(self.tree_files)
        Upload.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Upload)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Upload.setMenuBar(self.menubar)
        self.actionTest = QtGui.QAction(Upload)
        self.actionTest.setObjectName("actionTest")
        self.actionQuit = QtGui.QAction(Upload)
        self.actionQuit.setObjectName("actionQuit")
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Upload)
        QtCore.QMetaObject.connectSlotsByName(Upload)

    def retranslateUi(self, Upload):
        Upload.setWindowTitle(QtGui.QApplication.translate("Upload", "emdash", None, QtGui.QApplication.UnicodeUTF8))
        self.button_grid.setText(QtGui.QApplication.translate("Upload", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.button_path.setText(QtGui.QApplication.translate("Upload", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.button_session.setText(QtGui.QApplication.translate("Upload", "Session", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTest.setTitle(QtGui.QApplication.translate("Upload", "EMDash", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Upload", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("Upload", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Upload", "Quit", None, QtGui.QApplication.UnicodeUTF8))

from filesview import FilesView
