import cld

for lang in ['AFRIKAANS', 'ALBANIAN', 'AZERBAIJANI', 'BASQUE', 'BELARUSIAN', 'BULGARIAN', 'CATALAN', 'CROATIAN', 'CZECH', 'DANISH', 'DUTCH', 'ENGLISH', 'ESTONIAN', 'FINNISH', 'FRENCH', 'GALICIAN', 'GERMAN', 'GREEK', 'HAITIAN_CREOLE', 'HUNGARIAN', 'ICELANDIC', 'INDONESIAN', 'IRISH', 'ITALIAN', 'Ignore', 'LATVIAN', 'LITHUANIAN', 'MACEDONIAN', 'MALAY', 'MALTESE', 'NORWEGIAN', 'POLISH', 'PORTUGUESE', 'ROMANIAN', 'RUSSIAN', 'SERBIAN', 'SLOVAK', 'SLOVENIAN', 'SPANISH', 'SWAHILI', 'SWEDISH', 'TAGALOG', 'TURKISH', 'UKRAINIAN', 'VIETNAMESE', 'WELSH']:
  if lang not in cld.DETECTED_LANGUAGES:
    print '  missing: %s' % lang
