__version__ = "0.1.14"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'e469e62d780c9e0ebc0a84cec6e9b18daf6de032'
__git_head_subject__ = 'Finished release v0.1.14.'
__git_head_message__ = '* release/v0.1.14:\n  TRIVIAL more logging\n  empty commit after version v0.1.13'
__git_dirty_diff__ = ''