#Pipe pipe_Zh1GhXa63RG_biEj6ycw5g generated by pipe2py

from pipe2py import Context
from pipe2py.modules import *

import pipe_eAi4NqWn3RGcyGyUrLQIDg
import pipe_HBXVrI6n3RGE9RZ3rLQIDg
import pipe_02e616bedf63c7e574e83532042772a5

def pipe_Zh1GhXa63RG_biEj6ycw5g(context, _INPUT, conf=None, **kwargs):
    "Pipeline"
    if conf is None:
        conf = {}

    if context.describe_input:
        return [(u'', u'urlinput1', u'Enter URL of comic to get the associated news for:', u'url', u'')]

    forever = pipeforever.pipe_forever(context, None, conf=None)

    def pipe_sw_137(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_137 = pipe_eAi4NqWn3RGcyGyUrLQIDg.pipe_eAi4NqWn3RGcyGyUrLQIDg(context, _INPUT, conf={u'AddressOfNews': {u'type': u'url', u'subkey': u'link'}})
        return sw_137
    def pipe_sw_345(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_345 = pipedatebuilder.pipe_datebuilder(context, _INPUT, conf={u'DATE': {u'type': u'datetime', u'subkey': u'newsdate'}})
        return sw_345
    def pipe_sw_336(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_336 = pipedatebuilder.pipe_datebuilder(context, _INPUT, conf={u'DATE': {u'type': u'datetime', u'subkey': u'comicdate'}})
        return sw_336
    sw_99 = pipeurlinput.pipe_urlinput(context, forever, conf={u'default': {u'type': u'url', u'value': u''}, u'position': {u'type': u'number', u'value': u''}, u'prompt': {u'type': u'text', u'value': u'Enter URL of comic to get the associated news for:'}, u'name': {u'type': u'text', u'value': u'urlinput1'}, u'debug': {u'type': u'url', u'value': u'http://www.penny-arcade.com/comic/2010/10/13/more-things-are-dreamt-your-philosophy/'}})
    def pipe_sw_407(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_407 = pipefetchpage.pipe_fetchpage(context, _INPUT, conf={u'URL': {u'terminal': u'URL', u'type': u'url'}, u'to': {u'type': u'text', u'value': u'News</a></li>'}, u'token': {u'type': u'text', u'value': u''}, u'from': {u'type': u'text', u'value': u'<li class="float_left news">'}}, URL = sw_99)
        return sw_407
    sw_114 = pipe_HBXVrI6n3RGE9RZ3rLQIDg.pipe_HBXVrI6n3RGE9RZ3rLQIDg(context, forever, conf={u'AddressofComic': {u'terminal': u'AddressofComic', u'type': u'url'}}, AddressofComic = sw_99)
    def pipe_sw_373(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_373 = pipe_02e616bedf63c7e574e83532042772a5.pipe_02e616bedf63c7e574e83532042772a5(context, _INPUT, conf={u'date1': {u'type': u'datetime', u'subkey': u'comicdate'}, u'date2': {u'type': u'datetime', u'subkey': u'newsdate'}})
        return sw_373
    def pipe_sw_257(context, _INPUT, conf=None, **kwargs):
        "Submodule"
        sw_257 = pipefetchpage.pipe_fetchpage(context, _INPUT, conf={u'URL': {u'type': u'url', u'subkey': u'link'}, u'to': {u'type': u'text', u'value': u'<br />'}, u'token': {u'type': u'text', u'value': u''}, u'from': {u'type': u'text', u'value': u'<div class="metainfo">'}})
        return sw_257
    sw_935 = pipeloop.pipe_loop(context, sw_114, conf={u'assign_part': {u'type': u'text', u'value': u'first'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'fetchpage', u'id': u'sw-257', u'conf': {u'URL': {u'type': u'url', u'subkey': u'link'}, u'to': {u'type': u'text', u'value': u'<br />'}, u'token': {u'type': u'text', u'value': u''}, u'from': {u'type': u'text', u'value': u'<div class="metainfo">'}}}}, u'assign_to': {u'type': u'text', u'value': u'newsdate'}}, embed = pipe_sw_257)
    sw_399 = pipeloop.pipe_loop(context, sw_935, conf={u'assign_part': {u'type': u'text', u'value': u'first'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'fetchpage', u'id': u'sw-407', u'conf': {u'URL': {u'terminal': u'URL', u'type': u'url'}, u'to': {u'type': u'text', u'value': u'News</a></li>'}, u'token': {u'type': u'text', u'value': u''}, u'from': {u'type': u'text', u'value': u'<li class="float_left news">'}}}}, u'assign_to': {u'type': u'text', u'value': u'comicdate'}}, embed = pipe_sw_407)
    sw_281 = piperegex.pipe_regex(context, sw_399, conf={u'RULE': [{u'field': {u'type': u'text', u'value': u'newsdate.content'}, u'singlelinematch': {u'type': u'text', u'value': u'2'}, u'globalmatch': {u'type': u'text', u'value': u'1'}, u'match': {u'type': u'text', u'value': u'<.*?>'}, u'replace': {u'type': u'text', u'value': u''}}, {u'field': {u'type': u'text', u'value': u'comicdate.content'}, u'singlelinematch': {u'type': u'text', u'value': u'2'}, u'match': {u'type': u'text', u'value': u'^.*?\\.com\\/(\\d+\\/\\d+\\/\\d+)\\/.*$'}, u'replace': {u'type': u'text', u'value': u'$1'}}, {u'field': {u'type': u'text', u'value': u'comicdate'}, u'singlelinematch': {u'type': u'text', u'value': u'2'}, u'match': {u'type': u'text', u'value': u'.*'}, u'replace': {u'type': u'text', u'value': u'${comicdate.content}'}}, {u'field': {u'type': u'text', u'value': u'newsdate.content'}, u'singlelinematch': {u'type': u'text', u'value': u'2'}, u'match': {u'type': u'text', u'value': u'\\-.*'}, u'replace': {u'type': u'text', u'value': u''}}, {u'field': {u'type': u'text', u'value': u'newsdate'}, u'match': {u'type': u'text', u'value': u'.*'}, u'replace': {u'type': u'text', u'value': u'${newsdate.content}'}}, {u'field': {u'type': u'text', u'value': u'newsdate'}, u'match': {u'type': u'text', u'value': u'.*?day\\,\\s+'}, u'replace': {u'type': u'text', u'value': u''}}]})
    sw_320 = pipeloop.pipe_loop(context, sw_281, conf={u'assign_part': {u'type': u'text', u'value': u'all'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'datebuilder', u'id': u'sw-336', u'conf': {u'DATE': {u'type': u'datetime', u'subkey': u'comicdate'}}}}, u'assign_to': {u'type': u'text', u'value': u'comicdate'}}, embed = pipe_sw_336)
    sw_328 = pipeloop.pipe_loop(context, sw_320, conf={u'assign_part': {u'type': u'text', u'value': u'all'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'datebuilder', u'id': u'sw-345', u'conf': {u'DATE': {u'type': u'datetime', u'subkey': u'newsdate'}}}}, u'assign_to': {u'type': u'text', u'value': u'newsdate'}}, embed = pipe_sw_345)
    sw_365 = pipeloop.pipe_loop(context, sw_328, conf={u'assign_part': {u'type': u'text', u'value': u'first'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'pipe:02e616bedf63c7e574e83532042772a5', u'id': u'sw-373', u'conf': {u'date1': {u'type': u'datetime', u'subkey': u'comicdate'}, u'date2': {u'type': u'datetime', u'subkey': u'newsdate'}}}}, u'assign_to': {u'type': u'text', u'value': u'match'}}, embed = pipe_sw_373)
    sw_387 = pipefilter.pipe_filter(context, sw_365, conf={u'COMBINE': {u'type': u'text', u'value': u'and'}, u'MODE': {u'type': u'text', u'value': u'block'}, u'RULE': {u'field': {u'type': u'text', u'value': u'match.match'}, u'value': {u'type': u'text', u'value': u'false'}, u'op': {u'type': u'text', u'value': u'is'}}})
    sw_129 = pipeloop.pipe_loop(context, sw_387, conf={u'assign_part': {u'type': u'text', u'value': u'first'}, u'with': {u'type': u'text', u'value': u''}, u'emit_part': {u'type': u'text', u'value': u'all'}, u'mode': {u'type': u'text', u'value': u'assign'}, u'embed': {u'type': u'module', u'value': {u'type': u'pipe:eAi4NqWn3RGcyGyUrLQIDg', u'id': u'sw-137', u'conf': {u'AddressOfNews': {u'type': u'url', u'subkey': u'link'}}}}, u'assign_to': {u'type': u'text', u'value': u'content'}}, embed = pipe_sw_137)
    sw_146 = pipesubelement.pipe_subelement(context, sw_129, conf={u'path': {u'type': u'text', u'value': u'content'}})
    _OUTPUT = pipeoutput.pipe_output(context, sw_146, conf=None)
    return _OUTPUT

if __name__ == "__main__":
    context = Context()
    p = pipe_Zh1GhXa63RG_biEj6ycw5g(context, None)
    for i in p:
        print i

