# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wallpaper_info.ui'
#
# Created: Wed Nov  9 23:13:21 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(696, 284)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.wallpaperNameLabel = QtGui.QLabel(Form)
        self.wallpaperNameLabel.setText(QtGui.QApplication.translate("Form", "Wallpaper name", None, QtGui.QApplication.UnicodeUTF8))
        self.wallpaperNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wallpaperNameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.wallpaperNameLabel.setObjectName(_fromUtf8("wallpaperNameLabel"))
        self.verticalLayout.addWidget(self.wallpaperNameLabel)
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.infoTab = QtGui.QWidget()
        self.infoTab.setObjectName(_fromUtf8("infoTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.infoTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.infoLayout = QtGui.QHBoxLayout()
        self.infoLayout.setObjectName(_fromUtf8("infoLayout"))
        self.thumbLayout = QtGui.QVBoxLayout()
        self.thumbLayout.setObjectName(_fromUtf8("thumbLayout"))
        self.thumb = QtGui.QLabel(self.infoTab)
        self.thumb.setMinimumSize(QtCore.QSize(170, 100))
        self.thumb.setMaximumSize(QtCore.QSize(170, 100))
        self.thumb.setFrameShape(QtGui.QFrame.Box)
        self.thumb.setFrameShadow(QtGui.QFrame.Sunken)
        self.thumb.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb.setOpenExternalLinks(True)
        self.thumb.setObjectName(_fromUtf8("thumb"))
        self.thumbLayout.addWidget(self.thumb)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.thumbLayout.addItem(spacerItem)
        self.infoLayout.addLayout(self.thumbLayout)
        self.infoLabelsLayout = QtGui.QVBoxLayout()
        self.infoLabelsLayout.setObjectName(_fromUtf8("infoLabelsLayout"))
        self.resolutionLabel = QtGui.QLabel(self.infoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolutionLabel.sizePolicy().hasHeightForWidth())
        self.resolutionLabel.setSizePolicy(sizePolicy)
        self.resolutionLabel.setText(QtGui.QApplication.translate("Form", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionLabel.setOpenExternalLinks(True)
        self.resolutionLabel.setObjectName(_fromUtf8("resolutionLabel"))
        self.infoLabelsLayout.addWidget(self.resolutionLabel)
        self.sizeLabel = QtGui.QLabel(self.infoTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizeLabel.sizePolicy().hasHeightForWidth())
        self.sizeLabel.setSizePolicy(sizePolicy)
        self.sizeLabel.setText(QtGui.QApplication.translate("Form", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeLabel.setObjectName(_fromUtf8("sizeLabel"))
        self.infoLabelsLayout.addWidget(self.sizeLabel)
        self.topTagsLabel = QtGui.QLabel(self.infoTab)
        self.topTagsLabel.setText(QtGui.QApplication.translate("Form", "Top tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.topTagsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.topTagsLabel.setWordWrap(True)
        self.topTagsLabel.setOpenExternalLinks(True)
        self.topTagsLabel.setObjectName(_fromUtf8("topTagsLabel"))
        self.infoLabelsLayout.addWidget(self.topTagsLabel)
        self.infoLayout.addLayout(self.infoLabelsLayout)
        self.infoLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.infoLayout)
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.setStretch(1, 1)
        self.tabWidget.addTab(self.infoTab, _fromUtf8(""))
        self.ursTab = QtGui.QWidget()
        self.ursTab.setObjectName(_fromUtf8("ursTab"))
        self.urlsLayout = QtGui.QVBoxLayout(self.ursTab)
        self.urlsLayout.setObjectName(_fromUtf8("urlsLayout"))
        self.sendBadUrlsCheck = QtGui.QCheckBox(self.ursTab)
        self.sendBadUrlsCheck.setText(QtGui.QApplication.translate("Form", "Send bad urls (max 5)", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBadUrlsCheck.setObjectName(_fromUtf8("sendBadUrlsCheck"))
        self.urlsLayout.addWidget(self.sendBadUrlsCheck)
        self.urls = QtGui.QScrollArea(self.ursTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urls.sizePolicy().hasHeightForWidth())
        self.urls.setSizePolicy(sizePolicy)
        self.urls.setWidgetResizable(True)
        self.urls.setObjectName(_fromUtf8("urls"))
        self.urlsContents = QtGui.QWidget()
        self.urlsContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.urlsContents.setObjectName(_fromUtf8("urlsContents"))
        self.formLayout = QtGui.QFormLayout(self.urlsContents)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.urls.setWidget(self.urlsContents)
        self.urlsLayout.addWidget(self.urls)
        self.tabWidget.addTab(self.ursTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.actionLayout = QtGui.QHBoxLayout()
        self.actionLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.actionLayout.setObjectName(_fromUtf8("actionLayout"))
        self.setWallpaperCheck = QtGui.QCheckBox(Form)
        self.setWallpaperCheck.setText(QtGui.QApplication.translate("Form", "Set wallpaper", None, QtGui.QApplication.UnicodeUTF8))
        self.setWallpaperCheck.setObjectName(_fromUtf8("setWallpaperCheck"))
        self.actionLayout.addWidget(self.setWallpaperCheck)
        self.addToMyWallpapersCheck = QtGui.QCheckBox(Form)
        self.addToMyWallpapersCheck.setText(QtGui.QApplication.translate("Form", "Add to my wallpapers", None, QtGui.QApplication.UnicodeUTF8))
        self.addToMyWallpapersCheck.setObjectName(_fromUtf8("addToMyWallpapersCheck"))
        self.actionLayout.addWidget(self.addToMyWallpapersCheck)
        self.rejectWallpaperCheck = QtGui.QCheckBox(Form)
        self.rejectWallpaperCheck.setText(QtGui.QApplication.translate("Form", "Reject wallpaper", None, QtGui.QApplication.UnicodeUTF8))
        self.rejectWallpaperCheck.setObjectName(_fromUtf8("rejectWallpaperCheck"))
        self.actionLayout.addWidget(self.rejectWallpaperCheck)
        self.myWallpaperUrl = QtGui.QLabel(Form)
        self.myWallpaperUrl.setText(QtGui.QApplication.translate("Form", "Page on new-wallpaper.org", None, QtGui.QApplication.UnicodeUTF8))
        self.myWallpaperUrl.setOpenExternalLinks(True)
        self.myWallpaperUrl.setObjectName(_fromUtf8("myWallpaperUrl"))
        self.actionLayout.addWidget(self.myWallpaperUrl)
        self.verticalLayout.addLayout(self.actionLayout)
        self.addTagsLayout = QtGui.QHBoxLayout()
        self.addTagsLayout.setObjectName(_fromUtf8("addTagsLayout"))
        self.addTagsCheck = QtGui.QCheckBox(Form)
        self.addTagsCheck.setText(QtGui.QApplication.translate("Form", "Add tags (max 5 at once):", None, QtGui.QApplication.UnicodeUTF8))
        self.addTagsCheck.setObjectName(_fromUtf8("addTagsCheck"))
        self.addTagsLayout.addWidget(self.addTagsCheck)
        self.addTagsEdit = QtGui.QLineEdit(Form)
        self.addTagsEdit.setObjectName(_fromUtf8("addTagsEdit"))
        self.addTagsLayout.addWidget(self.addTagsEdit)
        self.verticalLayout.addLayout(self.addTagsLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.addToMyWallpapersCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.addTagsCheck.setChecked)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.addTagsEdit)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _("Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ursTab), _("Wallpaper urls"))
        self.wallpaperNameLabel.setText(_("Wallpaper name"))
        self.resolutionLabel.setText(_("Resolution:"))
        self.sizeLabel.setText(_("Size:"))
        self.topTagsLabel.setText(_("Top tags:"))
        self.sendBadUrlsCheck.setText(_("Send bad urls (max 5)"))
        self.setWallpaperCheck.setText(_("Set wallpaper"))
        self.addToMyWallpapersCheck.setText(_("Add to my wallpapers"))
        self.rejectWallpaperCheck.setText(_("Reject wallpaper"))
        self.myWallpaperUrl.setText(_("Page on new-wallpaper.org"))
        self.addTagsCheck.setText(_("Add tags (max 5 at once):"))
