__version__ = "0.1.16"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '87e9b27875f78befe034e6bafa1c1faa0b37258c'
__git_head_subject__ = 'Finished release v0.1.16.'
__git_head_message__ = '* release/v0.1.16:\n  TRIVIAL fixing build\n  TRIVIAL fixing build\n  TRIVIAL fixing build\n  TRIVIAL add support for specifying which scripts will be generated on production\n  empty commit after version v0.1.15'
__git_dirty_diff__ = ''