__version__ = "0.2.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '79b541c10f19cb128e1152d7a030327b1235dd01'
__git_head_subject__ = 'Finished release v0.2.2.'
__git_head_message__ = '* release/v0.2.2:\n  TRIVIAL yet another fix get_os_version_string\n  empty commit after version v0.2.1'
__git_dirty_diff__ = ''