__version__ = "0.2.5"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5346e6e2d6ed69b333577324cab97c2f416da75a'
__git_head_subject__ = 'Finished release v0.2.5.'
__git_head_message__ = '* release/v0.2.5:\n  TRIVIAL RepositoryPluginremove_deprecated_files: buildout.in is also deprecated\n  TRIVIAL forgot package-data\n  TRIVIAL skipping some tests on Windows\n  empty commit after version v0.2.4'
__git_dirty_diff__ = ''