from distutils.core import setup

setup(  name='datahaven',
        version='rev6309',
        author='Vincent Cate, DataHaven.NET LTD',
        author_email='datahaven.net@gmail.com',
        maintainer='Veselin Penev',
        maintainer_email='penev.veselin@gmail.com',
        url='http://datahaven.net',
        description='Distributed encrypted backup utility',
        long_description='Distributed encrypted backup utility',
        download_url='http://datahaven.net/download.html',
        #download_url='http://pypi.python.org/packages/source/d/datahaven/datahaven-rev6309.tar.gz',
        license='Copyright DataHaven.NET LTD. of Anguilla, 2006-2012,\nAll rights reserved.',
        keywords='datahaven, data haven, data transfer, data protect, backup, safe backup, backup utility, backup data, backup software, backup online, distributed backup, peer to peer backup, storage, free storage, online storage, distributed storage, data storage, restore, restore data, distributed restore, restore online, safe restore, private key, encrypted data, data blocks, data recover, remote backup, remote storage, online backup software, donated space, donated, hdd space',
        #platform='Windows, Linux',
        #requires='ncrypt, pycurl, wxgtk, crypto, openssl, pyasn1, twisted, python', 
        classifiers=[
            'Development Status :: 3 - Alpha',
            'Environment :: Console',
            'Environment :: Web Environment',
            'Framework :: Twisted',
            'Intended Audience :: Customer Service',
            'Intended Audience :: Developers',
            'Intended Audience :: End Users/Desktop',
            'Intended Audience :: Information Technology',
            'Intended Audience :: System Administrators',
            'License :: Other/Proprietary License',
            'Natural Language :: English',
            'Operating System :: Microsoft :: Windows',
            'Operating System :: Microsoft :: Windows :: Windows 7',
            'Operating System :: Microsoft :: Windows :: Windows Vista',
            'Operating System :: Microsoft :: Windows :: Windows XP',
            'Operating System :: POSIX :: Linux',
            'Programming Language :: Python',
            'Programming Language :: Python :: 2.5',
            'Programming Language :: Python :: 2.6',
            'Programming Language :: Python :: 2.7',
            'Topic :: Security',
            'Topic :: Security :: Cryptography',
            'Topic :: System :: Archiving :: Backup',
            'Topic :: System :: Distributed Computing',
            'Topic :: Utilities',
            ],
            
        packages=[
            'datahaven',
    		'datahaven.p2p', 
    		'datahaven.forms',
       		'datahaven.lib',
    		'datahaven.lib.shtoom',
    		'datahaven.epsilon',
    		'datahaven.vertex',
    		'datahaven.cspace',
    		'datahaven.cspace.dht',
    		'datahaven.cspace.ext',
    		'datahaven.cspace.main',
    		'datahaven.cspace.network',
    		'datahaven.cspace.util',
    		'datahaven.cspaceapps',
    		'datahaven.nitro',
		    ],
		    
)




