# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlantaresia/ConfigureConnectionDialog.ui'
#
# Created: Mon Apr  2 11:56:42 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ConfigureConnectionDialog(object):
    def setupUi(self, ConfigureConnectionDialog):
        ConfigureConnectionDialog.setObjectName(_fromUtf8("ConfigureConnectionDialog"))
        ConfigureConnectionDialog.resize(333, 430)
        self.gridLayout_2 = QtGui.QGridLayout(ConfigureConnectionDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblName = QtGui.QLabel(ConfigureConnectionDialog)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 0, 0, 1, 1)
        self.txtName = QtGui.QLineEdit(ConfigureConnectionDialog)
        self.txtName.setObjectName(_fromUtf8("txtName"))
        self.gridLayout_2.addWidget(self.txtName, 0, 1, 1, 1)
        self.groupSqlServer = QtGui.QGroupBox(ConfigureConnectionDialog)
        self.groupSqlServer.setObjectName(_fromUtf8("groupSqlServer"))
        self.gridLayout = QtGui.QGridLayout(self.groupSqlServer)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblHost = QtGui.QLabel(self.groupSqlServer)
        self.lblHost.setObjectName(_fromUtf8("lblHost"))
        self.gridLayout.addWidget(self.lblHost, 0, 0, 1, 1)
        self.txtHost = QtGui.QLineEdit(self.groupSqlServer)
        self.txtHost.setObjectName(_fromUtf8("txtHost"))
        self.gridLayout.addWidget(self.txtHost, 0, 1, 1, 1)
        self.lblPort = QtGui.QLabel(self.groupSqlServer)
        self.lblPort.setObjectName(_fromUtf8("lblPort"))
        self.gridLayout.addWidget(self.lblPort, 1, 0, 1, 1)
        self.txtPort = QtGui.QLineEdit(self.groupSqlServer)
        self.txtPort.setObjectName(_fromUtf8("txtPort"))
        self.gridLayout.addWidget(self.txtPort, 1, 1, 1, 1)
        self.lblDatabase = QtGui.QLabel(self.groupSqlServer)
        self.lblDatabase.setEnabled(False)
        self.lblDatabase.setObjectName(_fromUtf8("lblDatabase"))
        self.gridLayout.addWidget(self.lblDatabase, 2, 0, 1, 1)
        self.txtDatabase = QtGui.QLineEdit(self.groupSqlServer)
        self.txtDatabase.setEnabled(False)
        self.txtDatabase.setObjectName(_fromUtf8("txtDatabase"))
        self.gridLayout.addWidget(self.txtDatabase, 2, 1, 1, 1)
        self.lblUsername = QtGui.QLabel(self.groupSqlServer)
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.gridLayout.addWidget(self.lblUsername, 3, 0, 1, 1)
        self.txtUsername = QtGui.QLineEdit(self.groupSqlServer)
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.gridLayout.addWidget(self.txtUsername, 3, 1, 1, 1)
        self.lblPassword = QtGui.QLabel(self.groupSqlServer)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.gridLayout.addWidget(self.lblPassword, 4, 0, 1, 1)
        self.txtPassword = QtGui.QLineEdit(self.groupSqlServer)
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.gridLayout.addWidget(self.txtPassword, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupSqlServer, 1, 0, 1, 2)
        self.checkTunnel = QtGui.QCheckBox(ConfigureConnectionDialog)
        self.checkTunnel.setObjectName(_fromUtf8("checkTunnel"))
        self.gridLayout_2.addWidget(self.checkTunnel, 2, 0, 1, 2)
        self.groupTunnel = QtGui.QGroupBox(ConfigureConnectionDialog)
        self.groupTunnel.setEnabled(False)
        self.groupTunnel.setObjectName(_fromUtf8("groupTunnel"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupTunnel)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblTunnelUsername = QtGui.QLabel(self.groupTunnel)
        self.lblTunnelUsername.setObjectName(_fromUtf8("lblTunnelUsername"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblTunnelUsername)
        self.txtTunnelUsername = QtGui.QLineEdit(self.groupTunnel)
        self.txtTunnelUsername.setObjectName(_fromUtf8("txtTunnelUsername"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtTunnelUsername)
        self.lblTunnelPassword = QtGui.QLabel(self.groupTunnel)
        self.lblTunnelPassword.setObjectName(_fromUtf8("lblTunnelPassword"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblTunnelPassword)
        self.txtTunnelPassword = QtGui.QLineEdit(self.groupTunnel)
        self.txtTunnelPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtTunnelPassword.setObjectName(_fromUtf8("txtTunnelPassword"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtTunnelPassword)
        self.labelPublicKeyInfo = QtGui.QLabel(self.groupTunnel)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.labelPublicKeyInfo.setFont(font)
        self.labelPublicKeyInfo.setObjectName(_fromUtf8("labelPublicKeyInfo"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelPublicKeyInfo)
        self.txtTunnelPort = QtGui.QLineEdit(self.groupTunnel)
        self.txtTunnelPort.setObjectName(_fromUtf8("txtTunnelPort"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtTunnelPort)
        self.lblTunnelPort = QtGui.QLabel(self.groupTunnel)
        self.lblTunnelPort.setObjectName(_fromUtf8("lblTunnelPort"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblTunnelPort)
        self.gridLayout_2.addWidget(self.groupTunnel, 3, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigureConnectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.lblName.setBuddy(self.txtName)
        self.lblHost.setBuddy(self.txtHost)
        self.lblPort.setBuddy(self.txtPort)
        self.lblDatabase.setBuddy(self.txtDatabase)
        self.lblUsername.setBuddy(self.txtUsername)
        self.lblPassword.setBuddy(self.txtPassword)
        self.lblTunnelUsername.setBuddy(self.txtTunnelUsername)
        self.lblTunnelPassword.setBuddy(self.txtTunnelPassword)
        self.lblTunnelPort.setBuddy(self.txtTunnelPort)

        self.retranslateUi(ConfigureConnectionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ConfigureConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureConnectionDialog)
        ConfigureConnectionDialog.setTabOrder(self.txtName, self.txtHost)
        ConfigureConnectionDialog.setTabOrder(self.txtHost, self.txtPort)
        ConfigureConnectionDialog.setTabOrder(self.txtPort, self.txtDatabase)
        ConfigureConnectionDialog.setTabOrder(self.txtDatabase, self.txtUsername)
        ConfigureConnectionDialog.setTabOrder(self.txtUsername, self.txtPassword)
        ConfigureConnectionDialog.setTabOrder(self.txtPassword, self.checkTunnel)
        ConfigureConnectionDialog.setTabOrder(self.checkTunnel, self.txtTunnelUsername)
        ConfigureConnectionDialog.setTabOrder(self.txtTunnelUsername, self.txtTunnelPassword)
        ConfigureConnectionDialog.setTabOrder(self.txtTunnelPassword, self.txtTunnelPort)
        ConfigureConnectionDialog.setTabOrder(self.txtTunnelPort, self.buttonBox)

    def retranslateUi(self, ConfigureConnectionDialog):
        ConfigureConnectionDialog.setWindowTitle(QtGui.QApplication.translate("ConfigureConnectionDialog", "Configure Connection: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblName.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Connection Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSqlServer.setTitle(QtGui.QApplication.translate("ConfigureConnectionDialog", "MySQL Server", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHost.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtHost.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPort.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPort.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "3306", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDatabase.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Database:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtDatabase.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Not implemented", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsername.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtUsername.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "root", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPassword.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkTunnel.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Connect through a SSH tunnel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTunnel.setTitle(QtGui.QApplication.translate("ConfigureConnectionDialog", "SSH Tunnel Options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTunnelUsername.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTunnelPassword.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPublicKeyInfo.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "You can leave this empty for Public-Key authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.txtTunnelPort.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTunnelPort.setText(QtGui.QApplication.translate("ConfigureConnectionDialog", "Port:", None, QtGui.QApplication.UnicodeUTF8))

