# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlantaresia/SQLAntaresiaWindow.ui'
#
# Created: Tue Mar 20 12:06:33 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SQLAntaresiaWindow(object):
    def setupUi(self, SQLAntaresiaWindow):
        SQLAntaresiaWindow.setObjectName(_fromUtf8("SQLAntaresiaWindow"))
        SQLAntaresiaWindow.resize(900, 600)
        SQLAntaresiaWindow.setWindowTitle(_fromUtf8("SQL Antaresia"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/32/icons/kexi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SQLAntaresiaWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SQLAntaresiaWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cmbConnection = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConnection.sizePolicy().hasHeightForWidth())
        self.cmbConnection.setSizePolicy(sizePolicy)
        self.cmbConnection.setEditable(True)
        self.cmbConnection.setObjectName(_fromUtf8("cmbConnection"))
        self.verticalLayout.addWidget(self.cmbConnection)
        self.tabsWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabsWidget.setTabsClosable(True)
        self.tabsWidget.setMovable(True)
        self.tabsWidget.setObjectName(_fromUtf8("tabsWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabsWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabsWidget)
        SQLAntaresiaWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(SQLAntaresiaWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 18))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Server = QtGui.QMenu(self.menuBar)
        self.menu_Server.setObjectName(_fromUtf8("menu_Server"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Settings = QtGui.QMenu(self.menuBar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        SQLAntaresiaWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(SQLAntaresiaWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        SQLAntaresiaWindow.setStatusBar(self.statusBar)
        self.toolBarConnection = QtGui.QToolBar(SQLAntaresiaWindow)
        self.toolBarConnection.setObjectName(_fromUtf8("toolBarConnection"))
        SQLAntaresiaWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarConnection)
        self.dockWidget = QtGui.QDockWidget(SQLAntaresiaWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setRootIsDecorated(False)
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout_3.addWidget(self.treeView, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        SQLAntaresiaWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionRefreshTableList = QtGui.QAction(SQLAntaresiaWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefreshTableList.setIcon(icon1)
        self.actionRefreshTableList.setObjectName(_fromUtf8("actionRefreshTableList"))
        self.actionRefreshDatabases = QtGui.QAction(SQLAntaresiaWindow)
        self.actionRefreshDatabases.setIcon(icon1)
        self.actionRefreshDatabases.setObjectName(_fromUtf8("actionRefreshDatabases"))
        self.actionDropTable = QtGui.QAction(SQLAntaresiaWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/edit-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDropTable.setIcon(icon2)
        self.actionDropTable.setObjectName(_fromUtf8("actionDropTable"))
        self.actionCloseTab = QtGui.QAction(SQLAntaresiaWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/tab-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCloseTab.setIcon(icon3)
        self.actionCloseTab.setObjectName(_fromUtf8("actionCloseTab"))
        self.actionShowStatusbar = QtGui.QAction(SQLAntaresiaWindow)
        self.actionShowStatusbar.setCheckable(True)
        self.actionShowStatusbar.setChecked(True)
        self.actionShowStatusbar.setObjectName(_fromUtf8("actionShowStatusbar"))
        self.actionConfigureSQLAntaresia = QtGui.QAction(SQLAntaresiaWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigureSQLAntaresia.setIcon(icon4)
        self.actionConfigureSQLAntaresia.setObjectName(_fromUtf8("actionConfigureSQLAntaresia"))
        self.actionConfigureConnections = QtGui.QAction(SQLAntaresiaWindow)
        self.actionConfigureConnections.setIcon(icon4)
        self.actionConfigureConnections.setObjectName(_fromUtf8("actionConfigureConnections"))
        self.actionAboutSQLAntaresia = QtGui.QAction(SQLAntaresiaWindow)
        self.actionAboutSQLAntaresia.setIcon(icon)
        self.actionAboutSQLAntaresia.setObjectName(_fromUtf8("actionAboutSQLAntaresia"))
        self.actionAboutQt = QtGui.QAction(SQLAntaresiaWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/64/icons/qtlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAboutQt.setIcon(icon5)
        self.actionAboutQt.setObjectName(_fromUtf8("actionAboutQt"))
        self.actionQuit = QtGui.QAction(SQLAntaresiaWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon6)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShowDatabases = QtGui.QAction(SQLAntaresiaWindow)
        self.actionShowDatabases.setCheckable(True)
        self.actionShowDatabases.setChecked(True)
        self.actionShowDatabases.setObjectName(_fromUtf8("actionShowDatabases"))
        self.actionDropDatabase = QtGui.QAction(SQLAntaresiaWindow)
        self.actionDropDatabase.setIcon(icon2)
        self.actionDropDatabase.setObjectName(_fromUtf8("actionDropDatabase"))
        self.actionReconnect = QtGui.QAction(SQLAntaresiaWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/network-connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReconnect.setIcon(icon7)
        self.actionReconnect.setObjectName(_fromUtf8("actionReconnect"))
        self.actionDisconnect = QtGui.QAction(SQLAntaresiaWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/network-disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon8)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionTruncateTable = QtGui.QAction(SQLAntaresiaWindow)
        self.actionTruncateTable.setIcon(icon2)
        self.actionTruncateTable.setObjectName(_fromUtf8("actionTruncateTable"))
        self.actionNewQueryTab = QtGui.QAction(SQLAntaresiaWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/tab-new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewQueryTab.setIcon(icon9)
        self.actionNewQueryTab.setObjectName(_fromUtf8("actionNewQueryTab"))
        self.actionOptimizeTable = QtGui.QAction(SQLAntaresiaWindow)
        self.actionOptimizeTable.setObjectName(_fromUtf8("actionOptimizeTable"))
        self.actionRepairTable = QtGui.QAction(SQLAntaresiaWindow)
        self.actionRepairTable.setObjectName(_fromUtf8("actionRepairTable"))
        self.actionGo = QtGui.QAction(SQLAntaresiaWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/system-run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGo.setIcon(icon10)
        self.actionGo.setObjectName(_fromUtf8("actionGo"))
        self.actionShowCreate = QtGui.QAction(SQLAntaresiaWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/document-properties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowCreate.setIcon(icon11)
        self.actionShowCreate.setObjectName(_fromUtf8("actionShowCreate"))
        self.actionRefresh = QtGui.QAction(SQLAntaresiaWindow)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.menu_File.addAction(self.actionQuit)
        self.menu_Server.addAction(self.actionReconnect)
        self.menu_Server.addAction(self.actionDisconnect)
        self.menu_Server.addAction(self.actionRefresh)
        self.menu_Help.addAction(self.actionAboutSQLAntaresia)
        self.menu_Help.addAction(self.actionAboutQt)
        self.menu_Settings.addAction(self.actionShowDatabases)
        self.menu_Settings.addAction(self.actionShowStatusbar)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.actionConfigureConnections)
        self.menu_Settings.addAction(self.actionConfigureSQLAntaresia)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Server.menuAction())
        self.menuBar.addAction(self.menu_Settings.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.toolBarConnection.addAction(self.actionGo)

        self.retranslateUi(SQLAntaresiaWindow)
        self.tabsWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), SQLAntaresiaWindow.close)
        QtCore.QObject.connect(self.actionShowStatusbar, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.statusBar.setVisible)
        QtCore.QObject.connect(self.actionShowDatabases, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), self.dockWidget.setVisible)
        QtCore.QObject.connect(self.dockWidget, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionShowDatabases.setChecked)
        QtCore.QMetaObject.connectSlotsByName(SQLAntaresiaWindow)
        SQLAntaresiaWindow.setTabOrder(self.cmbConnection, self.treeView)
        SQLAntaresiaWindow.setTabOrder(self.treeView, self.tabsWidget)

    def retranslateUi(self, SQLAntaresiaWindow):
        self.cmbConnection.setStatusTip(QtGui.QApplication.translate("SQLAntaresiaWindow", "Connection string: Can be either a connection name or an URI of the type \"username:password@hostname[:port]\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.tab), QtGui.QApplication.translate("SQLAntaresiaWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Server.setTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "Se&rver", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarConnection.setWindowTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarConnection.setStatusTip(QtGui.QApplication.translate("SQLAntaresiaWindow", "Connect to the specified server", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("SQLAntaresiaWindow", "Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshTableList.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Refresh Table List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefreshDatabases.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Refresh Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDropTable.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Drop Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseTab.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Close Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseTab.setShortcut(QtGui.QApplication.translate("SQLAntaresiaWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowStatusbar.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Show St&atusbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigureSQLAntaresia.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Configure &SQL Antaresia", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigureConnections.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Configure &Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutSQLAntaresia.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "About SQL Antaresia", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("SQLAntaresiaWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowDatabases.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Show &Databases", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDropDatabase.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Drop Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDropDatabase.setToolTip(QtGui.QApplication.translate("SQLAntaresiaWindow", "Drop Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReconnect.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Re&connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDisconnect.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTruncateTable.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Truncate Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewQueryTab.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "&New Query Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptimizeTable.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Optimize Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRepairTable.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Repair Table", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGo.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowCreate.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "Show Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("SQLAntaresiaWindow", "&Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setShortcut(QtGui.QApplication.translate("SQLAntaresiaWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
