# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlantaresia/TableDetailsWidget.ui'
#
# Created: Mon Apr  2 15:36:40 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TableDetailsWidget(object):
    def setupUi(self, TableDetailsWidget):
        TableDetailsWidget.setObjectName(_fromUtf8("TableDetailsWidget"))
        TableDetailsWidget.resize(675, 446)
        TableDetailsWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabStructure = QtGui.QWidget()
        self.tabStructure.setObjectName(_fromUtf8("tabStructure"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabStructure)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblTableInfo = QtGui.QLabel(self.tabStructure)
        self.lblTableInfo.setText(_fromUtf8(""))
        self.lblTableInfo.setObjectName(_fromUtf8("lblTableInfo"))
        self.verticalLayout.addWidget(self.lblTableInfo)
        self.splitter = QtGui.QSplitter(self.tabStructure)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableStructure = QtGui.QTableView(self.splitter)
        self.tableStructure.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableStructure.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableStructure.setCornerButtonEnabled(False)
        self.tableStructure.setObjectName(_fromUtf8("tableStructure"))
        self.tableIndexes = QtGui.QTableView(self.splitter)
        self.tableIndexes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableIndexes.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableIndexes.setCornerButtonEnabled(False)
        self.tableIndexes.setObjectName(_fromUtf8("tableIndexes"))
        self.verticalLayout.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/layer_database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TableDetailsWidget.addTab(self.tabStructure, icon, _fromUtf8(""))
        self.tabData = QtGui.QWidget()
        self.tabData.setObjectName(_fromUtf8("tabData"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabData)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblQueryDesc = QtGui.QLabel(self.tabData)
        self.lblQueryDesc.setText(_fromUtf8("SELECT * FROM %1 WHERE"))
        self.lblQueryDesc.setObjectName(_fromUtf8("lblQueryDesc"))
        self.horizontalLayout_2.addWidget(self.lblQueryDesc)
        self.txtWhere = QtGui.QLineEdit(self.tabData)
        self.txtWhere.setObjectName(_fromUtf8("txtWhere"))
        self.horizontalLayout_2.addWidget(self.txtWhere)
        self.lblQueryLimit = QtGui.QLabel(self.tabData)
        self.lblQueryLimit.setObjectName(_fromUtf8("lblQueryLimit"))
        self.horizontalLayout_2.addWidget(self.lblQueryLimit)
        self.txtLimit = QtGui.QSpinBox(self.tabData)
        self.txtLimit.setMaximum(10000)
        self.txtLimit.setSingleStep(100)
        self.txtLimit.setProperty("value", 1000)
        self.txtLimit.setObjectName(_fromUtf8("txtLimit"))
        self.horizontalLayout_2.addWidget(self.txtLimit)
        self.btnRefreshData = QtGui.QPushButton(self.tabData)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/database_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefreshData.setIcon(icon1)
        self.btnRefreshData.setObjectName(_fromUtf8("btnRefreshData"))
        self.horizontalLayout_2.addWidget(self.btnRefreshData)
        self.btnEditQuery = QtGui.QPushButton(self.tabData)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/database_edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditQuery.setIcon(icon2)
        self.btnEditQuery.setObjectName(_fromUtf8("btnEditQuery"))
        self.horizontalLayout_2.addWidget(self.btnEditQuery)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tableData = QtGui.QTableView(self.tabData)
        self.tableData.setAlternatingRowColors(True)
        self.tableData.setSortingEnabled(True)
        self.tableData.setObjectName(_fromUtf8("tableData"))
        self.tableData.horizontalHeader().setCascadingSectionResizes(True)
        self.tableData.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableData)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblDataSubmitResult = QtGui.QLabel(self.tabData)
        self.lblDataSubmitResult.setText(_fromUtf8(""))
        self.lblDataSubmitResult.setObjectName(_fromUtf8("lblDataSubmitResult"))
        self.horizontalLayout_3.addWidget(self.lblDataSubmitResult)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnUndo = QtGui.QPushButton(self.tabData)
        self.btnUndo.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUndo.setIcon(icon3)
        self.btnUndo.setObjectName(_fromUtf8("btnUndo"))
        self.horizontalLayout_3.addWidget(self.btnUndo)
        self.btnApply = QtGui.QPushButton(self.tabData)
        self.btnApply.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/dialog-ok-apply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApply.setIcon(icon4)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout_3.addWidget(self.btnApply)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/16/icons/database_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TableDetailsWidget.addTab(self.tabData, icon5, _fromUtf8(""))
        self.lblQueryDesc.setBuddy(self.txtWhere)

        self.retranslateUi(TableDetailsWidget)
        TableDetailsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TableDetailsWidget)
        TableDetailsWidget.setTabOrder(self.tableStructure, self.txtWhere)
        TableDetailsWidget.setTabOrder(self.txtWhere, self.btnRefreshData)
        TableDetailsWidget.setTabOrder(self.btnRefreshData, self.btnEditQuery)
        TableDetailsWidget.setTabOrder(self.btnEditQuery, self.tableData)
        TableDetailsWidget.setTabOrder(self.tableData, self.btnApply)
        TableDetailsWidget.setTabOrder(self.btnApply, self.btnUndo)

    def retranslateUi(self, TableDetailsWidget):
        TableDetailsWidget.setTabText(TableDetailsWidget.indexOf(self.tabStructure), QtGui.QApplication.translate("TableDetailsWidget", "Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQueryLimit.setText(QtGui.QApplication.translate("TableDetailsWidget", "LIMIT", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefreshData.setText(QtGui.QApplication.translate("TableDetailsWidget", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditQuery.setText(QtGui.QApplication.translate("TableDetailsWidget", "Edit Query", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUndo.setText(QtGui.QApplication.translate("TableDetailsWidget", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUndo.setShortcut(QtGui.QApplication.translate("TableDetailsWidget", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApply.setText(QtGui.QApplication.translate("TableDetailsWidget", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        TableDetailsWidget.setTabText(TableDetailsWidget.indexOf(self.tabData), QtGui.QApplication.translate("TableDetailsWidget", "Data", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
