INSERT IGNORE INTO scanner_config_sections (id, name) values(1, 'Global settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(2, 'System settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(3, 'Incoming work dir settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(4, 'Quarantine and Archive settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(5, 'Processing incoming mail settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(6, 'Virus scanning and vulnerability testing');
INSERT IGNORE INTO scanner_config_sections (id, name) values(7, 'Sophos Anti-Virus');
INSERT IGNORE INTO scanner_config_sections (id, name) values(8, 'ClamAV Anti-Virus');
INSERT IGNORE INTO scanner_config_sections (id, name) values(9, 'F-Protd-6 Anti-Virus');
INSERT IGNORE INTO scanner_config_sections (id, name) values(10, 'Dangerous and offensive content');
INSERT IGNORE INTO scanner_config_sections (id, name) values(11, 'Attachment Filename Checking');
INSERT IGNORE INTO scanner_config_sections (id, name) values(12, 'Reports and Responses');
INSERT IGNORE INTO scanner_config_sections (id, name) values(13, 'Changes to Message Headers');
INSERT IGNORE INTO scanner_config_sections (id, name) values(14, 'Notifications of blocked messages');
INSERT IGNORE INTO scanner_config_sections (id, name) values(15, 'Changes to the Subject: line');
INSERT IGNORE INTO scanner_config_sections (id, name) values(16, 'Changes to the Message Body');
INSERT IGNORE INTO scanner_config_sections (id, name) values(17, 'Mail Archiving and Monitoring');
INSERT IGNORE INTO scanner_config_sections (id, name) values(18, 'Notices to System Administrators');
INSERT IGNORE INTO scanner_config_sections (id, name) values(19, 'Spam Detection and Virus Scanner Definitions');
INSERT IGNORE INTO scanner_config_sections (id, name) values(20, 'Spam Detection and Spam RBLs');
INSERT IGNORE INTO scanner_config_sections (id, name) values(21, 'Watermarking');
INSERT IGNORE INTO scanner_config_sections (id, name) values(22, 'SpamAssassin');
INSERT IGNORE INTO scanner_config_sections (id, name) values(23, 'Custom Spam Scanner Plugin');
INSERT IGNORE INTO scanner_config_sections (id, name) values(24, 'What to do with spam');
INSERT IGNORE INTO scanner_config_sections (id, name) values(25, 'Logging');
INSERT IGNORE INTO scanner_config_sections (id, name) values(26, 'Advanced SpamAssassin Settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(27, 'Advanced Settings');
INSERT IGNORE INTO scanner_config_sections (id, name) values(28, 'Configuration serial numbers');