# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import rsb.protocol.Notification_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='rsb/protocol/FragmentedNotification.proto',
  package='rsb.protocol',
  serialized_pb='\n)rsb/protocol/FragmentedNotification.proto\x12\x0crsb.protocol\x1a\x1frsb/protocol/Notification.proto\"{\n\x16\x46ragmentedNotification\x12\x30\n\x0cnotification\x18\x01 \x02(\x0b\x32\x1a.rsb.protocol.Notification\x12\x19\n\x0enum_data_parts\x18\x02 \x02(\r:\x01\x31\x12\x14\n\tdata_part\x18\x03 \x02(\r:\x01\x30\x42\x1c\x42\x1a\x46ragmentedNotificationType')




_FRAGMENTEDNOTIFICATION = descriptor.Descriptor(
  name='FragmentedNotification',
  full_name='rsb.protocol.FragmentedNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='notification', full_name='rsb.protocol.FragmentedNotification.notification', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='num_data_parts', full_name='rsb.protocol.FragmentedNotification.num_data_parts', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_part', full_name='rsb.protocol.FragmentedNotification.data_part', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=215,
)

_FRAGMENTEDNOTIFICATION.fields_by_name['notification'].message_type = rsb.protocol.Notification_pb2._NOTIFICATION
DESCRIPTOR.message_types_by_name['FragmentedNotification'] = _FRAGMENTEDNOTIFICATION

class FragmentedNotification(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRAGMENTEDNOTIFICATION
  
  # @@protoc_insertion_point(class_scope:rsb.protocol.FragmentedNotification)

# @@protoc_insertion_point(module_scope)
