__version__ = "0.1.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '0186a5b257f7a5059192cd1304f5cbffc18bf0ac'
__git_head_subject__ = 'Finished release v0.1.1.'
__git_head_message__ = '* release/v0.1.1:\n  TRIVIAL execute_command not passing PYTHONPATH\n  updated project files from skeleton\n  README\n  python bump\n  buildout\n  buildout update'
__git_dirty_diff__ = ''