# -*- coding: utf-8 -*-
"""
This file has been generated by the RefBuild 0.1 utility.

You can either regenerate this file by running::

    $ buildref

or edit items such as the list of modules that are included for processing.
"""

header = 'This is the source reference for the NeuronPy project.'
modules = ['doc']
outpath = '../doc/source'
title = 'Source Reference'
