
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0'
version_full = '20ab8af2d370e5f89d2fd149e60bc855051b7d65'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

