EMAIL_EVENT_UNKNOWN = 0
EMAIL_EVENT_PROCESSED = 100
EMAIL_EVENT_DROPPED = 200
EMAIL_EVENT_DEFERRED = 300
EMAIL_EVENT_DELIVERED = 400
EMAIL_EVENT_BOUNCED = 500
EMAIL_EVENT_CLICKED = 600
EMAIL_EVENT_OPENED = 700
EMAIL_EVENT_UNSUBSCRIBE = 800
EMAIL_EVENT_SPAM = 900

POST_EVENT_URL = "/sendgrid/event/"
