__version__ = "0.1.17"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'cca3b9dc50f86ea2ae088fe94f677511e07825c8'
__git_head_subject__ = 'Finished release v0.1.17.'
__git_head_message__ = '* release/v0.1.17:\n  TRIVIAL fixing production scripts\n  empty commit after version v0.1.16'
__git_dirty_diff__ = ''