__version__ = "0.1.18"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'd4ba52e97b49952960c3e6f731bb52f1004722d6'
__git_head_subject__ = 'Finished release v0.1.18.'
__git_head_message__ = '* release/v0.1.18:\n  TRIVIAL fixing previous commit\n  TRIVIAL add support for require-administrative-privileges\n  empty commit after version v0.1.17'
__git_dirty_diff__ = ''