# -*- coding: utf-8 -*- 

from django.utils.translation import ugettext_lazy as _

_('Settings')
_('Access')
_('References')
_('Code name')
_('Template')
_('Confirm')
_('Description')
_('First name')
_('Last name')
_('Staff')
_('staff')
_('superuser')
_('Username')
_('Applications')
_('Application users')
_('User applications')
_('Users')
_('Group users')
_('Group')
_('Groups')
_('User groups')
_('Login information')
_('Personal information')
_('Additional information')
_('Date joined')
_('Last login')
_('Group permissions')
_('Content type')
_('Show inactive')
