from fanstatic import Library, Resource

from js.jquery import jquery

library = Library('horae.js.jqplot', 'static')

style_uncompressed = Resource(library, 'jquery.jqplot.css')
style = Resource(library, 'jquery.jqplot.min.css')

jqplot_uncompressed = Resource(library, 'jquery.jqplot.js', depends=[jquery, ])
jqplot = Resource(library, 'jquery.jqplot.min.js', depends=[jquery, ])

excanvas_uncompressed = Resource(library, 'excanvas.js', depends=[jqplot_uncompressed, ])
excanvas = Resource(library, 'excanvas.min.js', depends=[jqplot, ])

# plugins

barRenderer_uncompressed = Resource(library, 'plugins/jqplot.barRenderer.js', depends=[jqplot_uncompressed, ])
barRenderer = Resource(library, 'plugins/jqplot.barRenderer.min.js', depends=[jqplot, ])
BezierCurveRenderer_uncompressed = Resource(library, 'plugins/jqplot.BezierCurveRenderer.js', depends=[jqplot_uncompressed, ])
BezierCurveRenderer = Resource(library, 'plugins/jqplot.BezierCurveRenderer.min.js', depends=[jqplot, ])
blockRenderer_uncompressed = Resource(library, 'plugins/jqplot.blockRenderer.js', depends=[jqplot_uncompressed, ])
blockRenderer = Resource(library, 'plugins/jqplot.blockRenderer.min.js', depends=[jqplot, ])
bubbleRenderer_uncompressed = Resource(library, 'plugins/jqplot.bubbleRenderer.js', depends=[jqplot_uncompressed, ])
bubbleRenderer = Resource(library, 'plugins/jqplot.bubbleRenderer.min.js', depends=[jqplot, ])
canvasAxisLabelRenderer_uncompressed = Resource(library, 'plugins/jqplot.canvasAxisLabelRenderer.js', depends=[jqplot_uncompressed, ])
canvasAxisLabelRenderer = Resource(library, 'plugins/jqplot.canvasAxisLabelRenderer.min.js', depends=[jqplot, ])
canvasAxisTickRenderer_uncompressed = Resource(library, 'plugins/jqplot.canvasAxisTickRenderer.js', depends=[jqplot_uncompressed, ])
canvasAxisTickRenderer = Resource(library, 'plugins/jqplot.canvasAxisTickRenderer.min.js', depends=[jqplot, ])
canvasOverlay_uncompressed = Resource(library, 'plugins/jqplot.canvasOverlay.js', depends=[jqplot_uncompressed, ])
canvasOverlay = Resource(library, 'plugins/jqplot.canvasOverlay.min.js', depends=[jqplot, ])
canvasTextRenderer_uncompressed = Resource(library, 'plugins/jqplot.canvasTextRenderer.js', depends=[jqplot_uncompressed, ])
canvasTextRenderer = Resource(library, 'plugins/jqplot.canvasTextRenderer.min.js', depends=[jqplot, ])
categoryAxisRenderer_uncompressed = Resource(library, 'plugins/jqplot.categoryAxisRenderer.js', depends=[jqplot_uncompressed, ])
categoryAxisRenderer = Resource(library, 'plugins/jqplot.categoryAxisRenderer.min.js', depends=[jqplot, ])
ciParser_uncompressed = Resource(library, 'plugins/jqplot.ciParser.js', depends=[jqplot_uncompressed, ])
ciParser = Resource(library, 'plugins/jqplot.ciParser.min.js', depends=[jqplot, ])
cursor_uncompressed = Resource(library, 'plugins/jqplot.cursor.js', depends=[jqplot_uncompressed, ])
cursor = Resource(library, 'plugins/jqplot.cursor.min.js', depends=[jqplot, ])
dateAxisRenderer_uncompressed = Resource(library, 'plugins/jqplot.dateAxisRenderer.js', depends=[jqplot_uncompressed, ])
dateAxisRenderer = Resource(library, 'plugins/jqplot.dateAxisRenderer.min.js', depends=[jqplot, ])
donutRenderer_uncompressed = Resource(library, 'plugins/jqplot.donutRenderer.js', depends=[jqplot_uncompressed, ])
donutRenderer = Resource(library, 'plugins/jqplot.donutRenderer.min.js', depends=[jqplot, ])
dragable_uncompressed = Resource(library, 'plugins/jqplot.dragable.js', depends=[jqplot_uncompressed, ])
dragable = Resource(library, 'plugins/jqplot.dragable.min.js', depends=[jqplot, ])
enhancedLegendRenderer_uncompressed = Resource(library, 'plugins/jqplot.enhancedLegendRenderer.js', depends=[jqplot_uncompressed, ])
enhancedLegendRenderer = Resource(library, 'plugins/jqplot.enhancedLegendRenderer.min.js', depends=[jqplot, ])
funnelRenderer_uncompressed = Resource(library, 'plugins/jqplot.funnelRenderer.js', depends=[jqplot_uncompressed, ])
funnelRenderer = Resource(library, 'plugins/jqplot.funnelRenderer.min.js', depends=[jqplot, ])
highlighter_uncompressed = Resource(library, 'plugins/jqplot.highlighter.js', depends=[jqplot_uncompressed, ])
highlighter = Resource(library, 'plugins/jqplot.highlighter.min.js', depends=[jqplot, ])
json2_uncompressed = Resource(library, 'plugins/jqplot.json2.js', depends=[jqplot_uncompressed, ])
json2 = Resource(library, 'plugins/jqplot.json2.min.js', depends=[jqplot, ])
logAxisRenderer_uncompressed = Resource(library, 'plugins/jqplot.logAxisRenderer.js', depends=[jqplot_uncompressed, ])
logAxisRenderer = Resource(library, 'plugins/jqplot.logAxisRenderer.min.js', depends=[jqplot, ])
mekkoAxisRenderer_uncompressed = Resource(library, 'plugins/jqplot.mekkoAxisRenderer.js', depends=[jqplot_uncompressed, ])
mekkoAxisRenderer = Resource(library, 'plugins/jqplot.mekkoAxisRenderer.min.js', depends=[jqplot, ])
mekkoRenderer_uncompressed = Resource(library, 'plugins/jqplot.mekkoRenderer.js', depends=[jqplot_uncompressed, ])
mekkoRenderer = Resource(library, 'plugins/jqplot.mekkoRenderer.min.js', depends=[jqplot, ])
meterGaugeRenderer_uncompressed = Resource(library, 'plugins/jqplot.meterGaugeRenderer.js', depends=[jqplot_uncompressed, ])
meterGaugeRenderer = Resource(library, 'plugins/jqplot.meterGaugeRenderer.min.js', depends=[jqplot, ])
ohlcRenderer_uncompressed = Resource(library, 'plugins/jqplot.ohlcRenderer.js', depends=[jqplot_uncompressed, ])
ohlcRenderer = Resource(library, 'plugins/jqplot.ohlcRenderer.min.js', depends=[jqplot, ])
pieRenderer_uncompressed = Resource(library, 'plugins/jqplot.pieRenderer.js', depends=[jqplot_uncompressed, ])
pieRenderer = Resource(library, 'plugins/jqplot.pieRenderer.min.js', depends=[jqplot, ])
pointLabels_uncompressed = Resource(library, 'plugins/jqplot.pointLabels.js', depends=[jqplot_uncompressed, ])
pointLabels = Resource(library, 'plugins/jqplot.pointLabels.min.js', depends=[jqplot, ])
pyramidAxisRenderer_uncompressed = Resource(library, 'plugins/jqplot.pyramidAxisRenderer.js', depends=[jqplot_uncompressed, ])
pyramidAxisRenderer = Resource(library, 'plugins/jqplot.pyramidAxisRenderer.min.js', depends=[jqplot, ])
pyramidGridRenderer_uncompressed = Resource(library, 'plugins/jqplot.pyramidGridRenderer.js', depends=[jqplot_uncompressed, ])
pyramidGridRenderer = Resource(library, 'plugins/jqplot.pyramidGridRenderer.min.js', depends=[jqplot, ])
pyramidRenderer_uncompressed = Resource(library, 'plugins/jqplot.pyramidRenderer.js', depends=[jqplot_uncompressed, ])
pyramidRenderer = Resource(library, 'plugins/jqplot.pyramidRenderer.min.js', depends=[jqplot, ])
trendline_uncompressed = Resource(library, 'plugins/jqplot.trendline.js', depends=[jqplot_uncompressed, ])
trendline = Resource(library, 'plugins/jqplot.trendline.min.js', depends=[jqplot, ])
